# permissions for end users to edit WeMainnets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: WeMainnet-editor-role
rules:
- apiGroups:
  - apps.wavesenterprise.com
  resources:
  - WeMainnets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.wavesenterprise.com
  resources:
  - WeMainnets/status
  verbs:
  - get
